#!/bin/sh
# Copyright (c) 2026 REVYTECH, Inc.
# SPDX-License-Identifier: BSD-3-Clause
#
# builder-guest/create.sh — create Linux builder VM disk/image metadata.
# DOCS: docs/BUILDER-GUEST.md
set -eu
. "$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)/common.sh"
lf_need_freebsd
lf_mkdirs
mkdir -p "$LF_OUT/builder"

IMG="$LF_OUT/builder/disk.img"

lf_log "=== builder-guest create (Alpine ${BUILDER_ALPINE_VERSION}) ==="

[ -n "${BUILDER_ALPINE_SHA256:-}" ] || lf_die "BUILDER_ALPINE_SHA256 unset"
ISO_VENDOR="$LF_VENDOR/${BUILDER_ALPINE_ISO}"
if [ ! -f "$ISO_VENDOR" ]; then
	lf_log "Fetching pinned Alpine ISO via make fetch path..."
	lf_fetch "$BUILDER_ALPINE_URL" "$ISO_VENDOR" "$BUILDER_ALPINE_SHA256"
fi
lf_verify_required "$ISO_VENDOR" "$BUILDER_ALPINE_SHA256"
cp -f "$ISO_VENDOR" "$LF_OUT/builder/alpine-virt.iso"

if [ ! -f "$IMG" ]; then
	truncate -s "${BUILDER_DISK_GB}G" "$IMG"
fi

cat > "$LF_OUT/builder/state.env" <<EOF
# Generated by create.sh — not for commit
BUILDER_VM_NAME=lfs-builder
BUILDER_DISK=$IMG
BUILDER_ISO=$LF_OUT/builder/alpine-virt.iso
BUILDER_MEM_MB=$BUILDER_MEM_MB
BUILDER_CPUS=$BUILDER_CPUS
BUILDER_SSH=
LAST_CHAPTER=
EOF

lf_log "Wrote $LF_OUT/builder/state.env"
lf_log "Next: scripts/builder-guest/start.sh (install Alpine to disk, enable ssh)"
lf_log "=== create done ==="
