#!/bin/sh
# Copyright (c) 2026 REVYTECH, Inc.
# SPDX-License-Identifier: BSD-3-Clause
#
# build-cross-toolchain.sh — prepare FreeBSD host tools for Linux targets.
#
# WHAT: Verify clang can target x86_64-linux-gnu; record tool versions; optional
#       musl sysroot scaffolding for static BusyBox later.
# WHY:  Kernel and early userspace builds need a known good LF_CLANG.
# HOST: FreeBSD only (the CloudBSD build host).
# OUT:  out/toolchain/env.sh (sourced by later scripts)
# DOCS: docs/BUILD-HOST.md, docs/TROUBLESHOOTING.md

set -eu
. "$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)/common.sh"
lf_need_freebsd
lf_mkdirs

lf_start_log toolchain

lf_log "=== build-cross-toolchain ==="
CLANG="$(lf_clang)"
export LF_CLANG="$CLANG"
lf_log "Using clang: $CLANG ($($CLANG --version | head -1))"

# Prove Linux ELF object generation works.
TMPC="$LF_OUT/toolchain/probe.c"
TMPO="$LF_OUT/toolchain/probe.o"
mkdir -p "$LF_OUT/toolchain"
printf 'int lf_probe(void){return 0;}\n' > "$TMPC"
if ! "$CLANG" --target="$TARGET_TRIPLE" -c "$TMPC" -o "$TMPO"; then
	lf_die "clang cannot compile for $TARGET_TRIPLE — install llvm19+ from pkg (docs/TROUBLESHOOTING.md)"
fi
file "$TMPO" || true

# Prefer LLVM tools from the same family when available.
LLVM_AR="$(command -v llvm-ar || true)"
LLVM_OBJCOPY="$(command -v llvm-objcopy || true)"
LLVM_STRIP="$(command -v llvm-strip || true)"
LLD="$(command -v ld.lld || true)"

cat > "$LF_OUT/toolchain/env.sh" <<EOF
# Generated by build-cross-toolchain.sh — do not commit.
# Sourced by kernel/busybox scripts.
export LF_CLANG="$CLANG"
export TARGET_TRIPLE="$TARGET_TRIPLE"
export TARGET_ARCH="$TARGET_ARCH"
export LF_JOBS="$(lf_jobs)"
export LF_LLVM_AR="${LLVM_AR:-llvm-ar}"
export LF_LLVM_OBJCOPY="${LLVM_OBJCOPY:-llvm-objcopy}"
export LF_LLVM_STRIP="${LLVM_STRIP:-llvm-strip}"
export LF_LLD="${LLD:-ld.lld}"
EOF

lf_log "Wrote $LF_OUT/toolchain/env.sh"
lf_log "=== toolchain OK ==="
