#!/bin/sh
# Copyright (c) 2026 REVYTECH, Inc.
# SPDX-License-Identifier: BSD-3-Clause
#
# fetch-sources.sh — download and verify all pinned upstream tarballs.
#
# WHAT: Populate vendor/ from versions.env URLs + SHA256.
# WHY:  Reproducible builds; refuse silent upstream swaps.
# HOST: FreeBSD or any host with curl + sha256 (primary: the CloudBSD build host).
# OUT:  vendor/*.tar.* and vendor/busybox-static (optional bootstrap).
# DOCS: docs/ARCHITECTURE.md, docs/GPL-REDISTRIBUTION.md, versions.env

set -eu
. "$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)/common.sh"

lf_mkdirs
lf_log "=== fetch-sources (LF_ROOT=$LF_ROOT) ==="

lf_fetch "$LINUX_URL" "$LF_VENDOR/$LINUX_TARBALL" "$LINUX_SHA256"
lf_fetch "$BUSYBOX_URL" "$LF_VENDOR/$BUSYBOX_TARBALL" "$BUSYBOX_SHA256"
lf_fetch "$OPENZFS_URL" "$LF_VENDOR/$OPENZFS_TARBALL" "$OPENZFS_SHA256"
lf_fetch "$LIMINE_URL" "$LF_VENDOR/$LIMINE_TARBALL" "$LIMINE_SHA256"
lf_fetch "$MUSL_URL" "$LF_VENDOR/$MUSL_TARBALL" "$MUSL_SHA256"
[ -n "${ZLIB_SHA256:-}" ] || lf_die "ZLIB_SHA256 is empty — set ZLIB_SHA256 in versions.env to proceed"
lf_fetch "$ZLIB_URL" "$LF_VENDOR/$ZLIB_TARBALL" "$ZLIB_SHA256"
# Desktop / BLFS pins — only when SHA is non-empty.
if [ -n "${LIBPNG_SHA256:-}" ]; then
	lf_fetch "$LIBPNG_URL" "$LF_VENDOR/$LIBPNG_TARBALL" "$LIBPNG_SHA256"
fi
if [ -n "${FREETYPE_SHA256:-}" ]; then
	lf_fetch "$FREETYPE_URL" "$LF_VENDOR/$FREETYPE_TARBALL" "$FREETYPE_SHA256"
fi

# BusyBox static bootstrap — must have a pinned SHA (executed as PID 1).
if [ -n "${BUSYBOX_STATIC_URL:-}" ]; then
	[ -n "${BUSYBOX_STATIC_SHA256:-}" ] || lf_die "BUSYBOX_STATIC_SHA256 empty — refuse unpinned bootstrap binary"
	lf_fetch "$BUSYBOX_STATIC_URL" "$LF_VENDOR/busybox-static" "$BUSYBOX_STATIC_SHA256"
	chmod +x "$LF_VENDOR/busybox-static"
fi

# Builder Alpine ISO (booted under bhyve) — pin required when URL is set.
if [ -n "${BUILDER_ALPINE_URL:-}" ]; then
	[ -n "${BUILDER_ALPINE_SHA256:-}" ] || lf_die "BUILDER_ALPINE_SHA256 empty — refuse unpinned builder ISO"
	lf_fetch "$BUILDER_ALPINE_URL" "$LF_VENDOR/${BUILDER_ALPINE_ISO}" "$BUILDER_ALPINE_SHA256"
fi

# LFS book wget-list / md5sums (metadata only; empty SHA allowed with warning).
lf_fetch "$LFS_WGET_LIST_URL" "$LF_VENDOR/lfs-${LFS_BOOK_VERSION}-wget-list" "${LFS_WGET_LIST_SHA256:-}"
lf_fetch "$LFS_MD5SUMS_URL" "$LF_VENDOR/lfs-${LFS_BOOK_VERSION}-md5sums" "${LFS_MD5SUMS_SHA256:-}"

# Open VM Tools (Milestone C / VMware guests) — only when SHA pinned.
if [ -n "${OPEN_VM_TOOLS_URL:-}" ] && [ -n "${OPEN_VM_TOOLS_SHA256:-}" ]; then
	lf_fetch "$OPEN_VM_TOOLS_URL" "$LF_VENDOR/$OPEN_VM_TOOLS_TARBALL" "$OPEN_VM_TOOLS_SHA256"
fi

# Machine-readable lock for Phase 4 hardening / audits.
{
	echo "# Generated by fetch-sources.sh $(lf_timestamp)"
	echo "# Do not edit by hand; refresh via make fetch"
	for f in \
		"$LINUX_TARBALL" \
		"$BUSYBOX_TARBALL" \
		"$OPENZFS_TARBALL" \
		"$LIMINE_TARBALL" \
		"$MUSL_TARBALL" \
		"$ZLIB_TARBALL"
	do
		printf '%s  %s\n' "$(lf_sha256 "$LF_VENDOR/$f")" "$f"
	done
	if [ -n "${LIBPNG_SHA256:-}" ] && [ -f "$LF_VENDOR/$LIBPNG_TARBALL" ]; then
		printf '%s  %s\n' "$(lf_sha256 "$LF_VENDOR/$LIBPNG_TARBALL")" "$LIBPNG_TARBALL"
	fi
	if [ -n "${FREETYPE_SHA256:-}" ] && [ -f "$LF_VENDOR/$FREETYPE_TARBALL" ]; then
		printf '%s  %s\n' "$(lf_sha256 "$LF_VENDOR/$FREETYPE_TARBALL")" "$FREETYPE_TARBALL"
	fi
	if [ -n "${OPEN_VM_TOOLS_SHA256:-}" ] && [ -f "$LF_VENDOR/$OPEN_VM_TOOLS_TARBALL" ]; then
		printf '%s  %s\n' "$(lf_sha256 "$LF_VENDOR/$OPEN_VM_TOOLS_TARBALL")" "$OPEN_VM_TOOLS_TARBALL"
	fi
	if [ -f "$LF_VENDOR/busybox-static" ]; then
		printf '%s  %s\n' "$(lf_sha256 "$LF_VENDOR/busybox-static")" "busybox-static"
	fi
	if [ -n "${BUILDER_ALPINE_ISO:-}" ] && [ -f "$LF_VENDOR/$BUILDER_ALPINE_ISO" ]; then
		printf '%s  %s\n' "$(lf_sha256 "$LF_VENDOR/$BUILDER_ALPINE_ISO")" "$BUILDER_ALPINE_ISO"
	fi
} > "$LF_VENDOR/checksums.lock"

lf_log "=== fetch complete; lockfile at vendor/checksums.lock ==="
lf_log "Remember: redistributing builds implies GPL/CDDL source obligations (docs/GPL-REDISTRIBUTION.md)."
