#!/bin/sh
# Copyright (c) 2026 REVYTECH, Inc.
# SPDX-License-Identifier: BSD-3-Clause
#
# fetch-sources.sh — download and verify all pinned upstream tarballs.
#
# WHAT: Populate vendor/ from versions.env URLs + SHA256.
# WHY:  Reproducible builds; refuse silent upstream swaps.
# HOST: FreeBSD or any host with curl + sha256 (primary: the CloudBSD build host).
# OUT:  vendor/*.tar.* and vendor/busybox-static (optional bootstrap).
# DOCS: docs/ARCHITECTURE.md, docs/GPL-REDISTRIBUTION.md, versions.env

set -eu
. "$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)/common.sh"

lf_mkdirs
lf_log "=== fetch-sources (LF_ROOT=$LF_ROOT) ==="

lf_fetch "$LINUX_URL" "$LF_VENDOR/$LINUX_TARBALL" "$LINUX_SHA256"
lf_fetch "$BUSYBOX_URL" "$LF_VENDOR/$BUSYBOX_TARBALL" "$BUSYBOX_SHA256"
lf_fetch "$OPENZFS_URL" "$LF_VENDOR/$OPENZFS_TARBALL" "$OPENZFS_SHA256"
lf_fetch "$LIMINE_URL" "$LF_VENDOR/$LIMINE_TARBALL" "$LIMINE_SHA256"
lf_fetch "$MUSL_URL" "$LF_VENDOR/$MUSL_TARBALL" "$MUSL_SHA256"

# BusyBox static bootstrap — must have a pinned SHA (executed as PID 1).
if [ -n "${BUSYBOX_STATIC_URL:-}" ]; then
	[ -n "${BUSYBOX_STATIC_SHA256:-}" ] || lf_die "BUSYBOX_STATIC_SHA256 empty — refuse unpinned bootstrap binary"
	lf_fetch "$BUSYBOX_STATIC_URL" "$LF_VENDOR/busybox-static" "$BUSYBOX_STATIC_SHA256"
	chmod +x "$LF_VENDOR/busybox-static"
fi

# Builder Alpine ISO (booted under bhyve) — pin required when URL is set.
if [ -n "${BUILDER_ALPINE_URL:-}" ]; then
	[ -n "${BUILDER_ALPINE_SHA256:-}" ] || lf_die "BUILDER_ALPINE_SHA256 empty — refuse unpinned builder ISO"
	lf_fetch "$BUILDER_ALPINE_URL" "$LF_VENDOR/${BUILDER_ALPINE_ISO}" "$BUILDER_ALPINE_SHA256"
fi

# LFS book wget-list / md5sums (metadata only; empty SHA allowed with warning).
lf_fetch "$LFS_WGET_LIST_URL" "$LF_VENDOR/lfs-${LFS_BOOK_VERSION}-wget-list" ""
lf_fetch "$LFS_MD5SUMS_URL" "$LF_VENDOR/lfs-${LFS_BOOK_VERSION}-md5sums" ""

# Machine-readable lock for Phase 4 hardening / audits.
{
	echo "# Generated by fetch-sources.sh $(lf_timestamp)"
	echo "# Do not edit by hand; refresh via make fetch"
	for f in \
		"$LINUX_TARBALL" \
		"$BUSYBOX_TARBALL" \
		"$OPENZFS_TARBALL" \
		"$LIMINE_TARBALL" \
		"$MUSL_TARBALL"
	do
		printf '%s  %s\n' "$(lf_sha256 "$LF_VENDOR/$f")" "$f"
	done
	if [ -f "$LF_VENDOR/busybox-static" ]; then
		printf '%s  %s\n' "$(lf_sha256 "$LF_VENDOR/busybox-static")" "busybox-static"
	fi
	if [ -n "${BUILDER_ALPINE_ISO:-}" ] && [ -f "$LF_VENDOR/$BUILDER_ALPINE_ISO" ]; then
		printf '%s  %s\n' "$(lf_sha256 "$LF_VENDOR/$BUILDER_ALPINE_ISO")" "$BUILDER_ALPINE_ISO"
	fi
} > "$LF_VENDOR/checksums.lock"

lf_log "=== fetch complete; lockfile at vendor/checksums.lock ==="
lf_log "Remember: redistributing builds implies GPL/CDDL source obligations (docs/GPL-REDISTRIBUTION.md)."
