#!/bin/sh
# Copyright (c) 2026 REVYTECH, Inc.
# SPDX-License-Identifier: BSD-3-Clause
#
# install-cross-wrappers.sh — $TRIPLE-{gcc,g++,ar,…} wrappers → FreeBSD clang.
#
# WHAT: out/toolchain/bin/${TARGET_TRIPLE}-* scripts for chapter scripts that
#       still expect a GNU-style cross prefix (Alpine chapter map reuse).
# WHY:  Chapters set CC=${LFS_TGT}-gcc; on FreeBSD that must be clang+sysroot.
# HOST: FreeBSD only.
# OUT:  out/toolchain/bin/
# DOCS: docs/FREEBSD-CROSS-USERSPACE.md
set -eu
. "$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)/common.sh"
lf_need_freebsd
lf_mkdirs

# shellcheck disable=SC1091
[ -f "$LF_OUT/toolchain/env.sh" ] || lf_die "missing out/toolchain/env.sh (gmake toolchain)"
# shellcheck disable=SC1091
. "$LF_OUT/toolchain/env.sh"

TRIPLE="${TARGET_TRIPLE:-x86_64-linux-gnu}"
# Prefer musl ABI spelling so clang defaults the dynamic linker to ld-musl
# (x86_64-unknown-linux-gnu would emit /lib64/ld-linux-x86-64.so.2).
CLANG_TRIPLE="${LF_CLANG_LINUX_TRIPLE:-x86_64-unknown-linux-musl}"
SYSROOT="${LF_SYSROOT:-$LF_OUT/sysroot}"
case "$SYSROOT" in
*".."*) lf_die "SYSROOT must not contain .." ;;
"$LF_OUT"/*) ;;
*) lf_die "SYSROOT must be under $LF_OUT (got $SYSROOT)" ;;
esac
[ -d "$SYSROOT/usr/include" ] || lf_die "missing $SYSROOT (gmake spike-sysroot first)"
lf_path_under "$SYSROOT" "$LF_OUT"
CLANG="$(lf_clang)"
CLANGXX="$(command -v clang++ || echo "$CLANG")"
AR="${LF_LLVM_AR:-$(command -v llvm-ar)}"
RANLIB="${LF_LLVM_RANLIB:-$(command -v llvm-ranlib || true)}"
STRIP="${LF_LLVM_STRIP:-$(command -v llvm-strip || true)}"
OBJCOPY="${LF_LLVM_OBJCOPY:-$(command -v llvm-objcopy || true)}"
BINDIR="$LF_OUT/toolchain/bin"
# Ignore LF_MUSL_DYNAMIC_LINKER overrides — must match the sysroot arch linker.
MUSL_LD="/lib/$(lf_musl_ld_name)"

lf_token_ok() {
	printf '%s' "$1" | grep -Eq '^[A-Za-z0-9._+-]+$'
}

lf_token_ok "$TRIPLE" || lf_die "refusing TARGET_TRIPLE=$TRIPLE"
lf_token_ok "$CLANG_TRIPLE" || lf_die "refusing CLANG_TRIPLE=$CLANG_TRIPLE"
mkdir -p "$BINDIR"

# Quote for generated scripts (FreeBSD /bin/sh has no printf %q — hand-escape).
lf_sq() {
	printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

# gcc/g++ wrappers: bake sysroot + lld + musl interpreter; pass through all args.
write_cc_wrapper() {
	_name="$1"
	_driver="$2"
	lf_token_ok "$_name" || lf_die "refusing wrapper name $_name"
	_q_driver="$(lf_sq "$_driver")"
	_q_triple="$(lf_sq "$CLANG_TRIPLE")"
	_q_sysroot="$(lf_sq "$SYSROOT")"
	_q_ld="$(lf_sq "$MUSL_LD")"
	cat >"$BINDIR/$_name" <<EOF
#!/bin/sh
# Generated by install-cross-wrappers.sh — do not commit.
# Linker flags only on real link steps (-c/-S/-E/-M* skip them).
_link=1
for _a in "\$@"; do
	case "\$_a" in
	-c|-S|-E|-M|-MM) _link=0 ;;
	esac
done
if [ "\$_link" = 1 ]; then
	# --undefined-version: lld is strict about version-script symbols; zlib's
	# configure probe (and similar) otherwise fails shared-lib detection.
	exec ${_q_driver} --target=${_q_triple} --sysroot=${_q_sysroot} -fuse-ld=lld \\
		-Wl,-dynamic-linker,${_q_ld} -Wl,--undefined-version "\$@"
fi
exec ${_q_driver} --target=${_q_triple} --sysroot=${_q_sysroot} "\$@"
EOF
	chmod 755 "$BINDIR/$_name"
}

write_tool_wrapper() {
	_name="$1"
	_tool="$2"
	[ -n "$_tool" ] || lf_die "missing tool for $_name (pkg install llvm, or set LF_LLVM_AR / LF_LLVM_RANLIB / LF_LLVM_STRIP)"
	lf_token_ok "$_name" || lf_die "refusing wrapper name $_name"
	_q_tool="$(lf_sq "$_tool")"
	cat >"$BINDIR/$_name" <<EOF
#!/bin/sh
# Generated by install-cross-wrappers.sh — do not commit.
exec ${_q_tool} "\$@"
EOF
	chmod 755 "$BINDIR/$_name"
}

write_cc_wrapper "${TRIPLE}-gcc" "$CLANG"
write_cc_wrapper "${TRIPLE}-cc" "$CLANG"
write_cc_wrapper "${TRIPLE}-g++" "$CLANGXX"
write_cc_wrapper "${TRIPLE}-c++" "$CLANGXX"
write_tool_wrapper "${TRIPLE}-ar" "$AR"
if [ -n "$RANLIB" ]; then
	write_tool_wrapper "${TRIPLE}-ranlib" "$RANLIB"
else
	# llvm-ar s when llvm-ranlib is absent
	_q_ar="$(lf_sq "$AR")"
	cat >"$BINDIR/${TRIPLE}-ranlib" <<EOF
#!/bin/sh
# Generated by install-cross-wrappers.sh — do not commit.
exec ${_q_ar} s "\$@"
EOF
	chmod 755 "$BINDIR/${TRIPLE}-ranlib"
fi
[ -n "$STRIP" ] && write_tool_wrapper "${TRIPLE}-strip" "$STRIP"
[ -n "$OBJCOPY" ] && write_tool_wrapper "${TRIPLE}-objcopy" "$OBJCOPY"

# Also provide LFS book-style prefix used by Alpine chapter scripts.
LFS_TGT_ALIAS="${LFS_TGT:-x86_64-lfs-linux-gnu}"
lf_token_ok "$LFS_TGT_ALIAS" || lf_die "refusing LFS_TGT=$LFS_TGT_ALIAS"
if [ "$LFS_TGT_ALIAS" != "$TRIPLE" ]; then
	for s in gcc cc g++ c++ ar ranlib strip objcopy; do
		[ -x "$BINDIR/${TRIPLE}-$s" ] || continue
		ln -sfn "${TRIPLE}-$s" "$BINDIR/${LFS_TGT_ALIAS}-$s"
	done
fi

_q_sysroot="$(lf_sq "$SYSROOT")"
_q_clang_triple="$(lf_sq "$CLANG_TRIPLE")"
_q_bindir="$(lf_sq "$BINDIR")"
_q_lfs_tgt="$(lf_sq "${LFS_TGT:-$LFS_TGT_ALIAS}")"
cat >"$LF_OUT/toolchain/wrappers.env" <<EOF
# Generated by install-cross-wrappers.sh — do not commit.
export LF_SYSROOT=${_q_sysroot}
export LF_CLANG_LINUX_TRIPLE=${_q_clang_triple}
export PATH=${_q_bindir}:\${PATH}
export LFS_TGT=${_q_lfs_tgt}
EOF

lf_log "wrappers in $BINDIR (source out/toolchain/wrappers.env)"
